// Code generated by generate-sdk-go.ts — DO NOT EDIT.

package pgbeam

import (
	"context"
	"fmt"
)

var _ = fmt.Sprintf

// Client is the PgBeam API client. Access operations through service fields.
type Client struct {
	Projects  *ProjectsService
	Databases *DatabasesService
	Analytics *AnalyticsService
	Platform  *PlatformService
	Account   *AccountService
	t         *transport
}

// NewClient creates a new PgBeam API client.
func NewClient(opts *ClientOptions) *Client {
	t := newTransport(opts)
	c := &Client{t: t}
	c.Projects = &ProjectsService{t: t}
	c.Databases = &DatabasesService{t: t}
	c.Analytics = &AnalyticsService{t: t}
	c.Platform = &PlatformService{t: t}
	c.Account = &AccountService{t: t}
	return c
}

// ProjectsService provides projects operations.
type ProjectsService struct{ t *transport }

func (s *ProjectsService) ListCacheRules(ctx context.Context, projectID string, databaseID string, params *ListCacheRulesParams) (*ListCacheRulesResponse, error) {
	return doQuery[ListCacheRulesResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/databases/%s/cache-rules", projectID, databaseID), params)
}

func (s *ProjectsService) UpdateCacheRule(ctx context.Context, projectID string, databaseID string, queryHash string, body UpdateCacheRuleRequest) (*UpdateCacheRuleResponse, error) {
	return doJSON[UpdateCacheRuleResponse](s.t, ctx, "PUT", fmt.Sprintf("/v1/projects/%s/databases/%s/cache-rules/%s", projectID, databaseID, queryHash), body)
}

func (s *ProjectsService) ListCustomDomains(ctx context.Context, projectID string, params *ListCustomDomainsParams) (*ListCustomDomainsResponse, error) {
	return doQuery[ListCustomDomainsResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/domains", projectID), params)
}

func (s *ProjectsService) CreateCustomDomain(ctx context.Context, projectID string, body CreateCustomDomainRequest) (*CustomDomain, error) {
	return doJSON[CustomDomain](s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/domains", projectID), body)
}

func (s *ProjectsService) DeleteCustomDomain(ctx context.Context, projectID string, domainID string) error {
	return doVoid(s.t, ctx, "DELETE", fmt.Sprintf("/v1/projects/%s/domains/%s", projectID, domainID), nil)
}

func (s *ProjectsService) VerifyCustomDomain(ctx context.Context, projectID string, domainID string) (*VerifyCustomDomainResponse, error) {
	return doJSON[VerifyCustomDomainResponse](s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/domains/%s/verify", projectID, domainID), nil)
}

func (s *ProjectsService) ListProjects(ctx context.Context, params *ListProjectsParams) (*ListProjectsResponse, error) {
	return doQuery[ListProjectsResponse](s.t, ctx, "/v1/projects", params)
}

func (s *ProjectsService) CreateProject(ctx context.Context, body CreateProjectRequest) (*CreateProjectResponse, error) {
	return doJSON[CreateProjectResponse](s.t, ctx, "POST", "/v1/projects", body)
}

func (s *ProjectsService) GetProject(ctx context.Context, projectID string) (*Project, error) {
	return doJSON[Project](s.t, ctx, "GET", fmt.Sprintf("/v1/projects/%s", projectID), nil)
}

func (s *ProjectsService) UpdateProject(ctx context.Context, projectID string, body UpdateProjectRequest) (*Project, error) {
	return doJSON[Project](s.t, ctx, "PATCH", fmt.Sprintf("/v1/projects/%s", projectID), body)
}

func (s *ProjectsService) DeleteProject(ctx context.Context, projectID string) error {
	return doVoid(s.t, ctx, "DELETE", fmt.Sprintf("/v1/projects/%s", projectID), nil)
}

func (s *ProjectsService) GetProjectMetrics(ctx context.Context, projectID string, params *GetProjectMetricsParams) (*ProjectMetricsResponse, error) {
	return doQuery[ProjectMetricsResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/metrics", projectID), params)
}

func (s *ProjectsService) ListReplicas(ctx context.Context, databaseID string) (*ListReplicasResponse, error) {
	return doJSON[ListReplicasResponse](s.t, ctx, "GET", fmt.Sprintf("/v1/databases/%s/replicas", databaseID), nil)
}

func (s *ProjectsService) CreateReplica(ctx context.Context, databaseID string, body CreateReplicaRequest) (*Replica, error) {
	return doJSON[Replica](s.t, ctx, "POST", fmt.Sprintf("/v1/databases/%s/replicas", databaseID), body)
}

func (s *ProjectsService) DeleteReplica(ctx context.Context, databaseID string, replicaID string) error {
	return doVoid(s.t, ctx, "DELETE", fmt.Sprintf("/v1/databases/%s/replicas/%s", databaseID, replicaID), nil)
}

// DatabasesService provides databases operations.
type DatabasesService struct{ t *transport }

func (s *DatabasesService) ListDatabases(ctx context.Context, projectID string, params *ListDatabasesParams) (*ListDatabasesResponse, error) {
	return doQuery[ListDatabasesResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/databases", projectID), params)
}

func (s *DatabasesService) CreateDatabase(ctx context.Context, projectID string, body CreateDatabaseRequest) (*Database, error) {
	return doJSON[Database](s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/databases", projectID), body)
}

func (s *DatabasesService) GetDatabase(ctx context.Context, projectID string, databaseID string) (*Database, error) {
	return doJSON[Database](s.t, ctx, "GET", fmt.Sprintf("/v1/projects/%s/databases/%s", projectID, databaseID), nil)
}

func (s *DatabasesService) UpdateDatabase(ctx context.Context, projectID string, databaseID string, body UpdateDatabaseRequest) (*Database, error) {
	return doJSON[Database](s.t, ctx, "PATCH", fmt.Sprintf("/v1/projects/%s/databases/%s", projectID, databaseID), body)
}

func (s *DatabasesService) DeleteDatabase(ctx context.Context, projectID string, databaseID string) error {
	return doVoid(s.t, ctx, "DELETE", fmt.Sprintf("/v1/projects/%s/databases/%s", projectID, databaseID), nil)
}

func (s *DatabasesService) TestDatabaseConnection(ctx context.Context, projectID string, databaseID string) (*TestConnectionResult, error) {
	return doJSON[TestConnectionResult](s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/databases/%s/test-connection", projectID, databaseID), nil)
}

// AnalyticsService provides analytics operations.
type AnalyticsService struct{ t *transport }

func (s *AnalyticsService) ListPlans(ctx context.Context) (*ListPlansResponse, error) {
	return doJSON[ListPlansResponse](s.t, ctx, "GET", "/v1/plans", nil)
}

func (s *AnalyticsService) GetOrganizationPlan(ctx context.Context, orgID string) (*OrganizationPlan, error) {
	return doJSON[OrganizationPlan](s.t, ctx, "GET", fmt.Sprintf("/v1/organizations/%s/plan", orgID), nil)
}

func (s *AnalyticsService) UpdateSpendLimit(ctx context.Context, orgID string, body UpdateSpendLimitRequest) (*OrganizationPlan, error) {
	return doJSON[OrganizationPlan](s.t, ctx, "PUT", fmt.Sprintf("/v1/organizations/%s/spend-limit", orgID), body)
}

func (s *AnalyticsService) SubmitCancellationFeedback(ctx context.Context, orgID string, body CancellationFeedbackRequest) error {
	return doVoid(s.t, ctx, "POST", fmt.Sprintf("/v1/organizations/%s/cancellation-feedback", orgID), body)
}

func (s *AnalyticsService) GetProjectInsights(ctx context.Context, projectID string, params *GetProjectInsightsParams) (*ProjectInsights, error) {
	return doQuery[ProjectInsights](s.t, ctx, fmt.Sprintf("/v1/projects/%s/insights", projectID), params)
}

func (s *AnalyticsService) GetOrganizationUsage(ctx context.Context, orgID string, params *GetOrganizationUsageParams) (*UsageResponse, error) {
	return doQuery[UsageResponse](s.t, ctx, fmt.Sprintf("/v1/organizations/%s/usage", orgID), params)
}

func (s *AnalyticsService) GetProjectUsage(ctx context.Context, projectID string, params *GetProjectUsageParams) (*ProjectUsageResponse, error) {
	return doQuery[ProjectUsageResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/usage", projectID), params)
}

// PlatformService provides platform operations.
type PlatformService struct{ t *transport }

func (s *PlatformService) GetHealth(ctx context.Context) (*HealthResponse, error) {
	return doJSON[HealthResponse](s.t, ctx, "GET", "/v1/health", nil)
}

func (s *PlatformService) ListRegions(ctx context.Context) (*ListRegionsResponse, error) {
	return doJSON[ListRegionsResponse](s.t, ctx, "GET", "/v1/regions", nil)
}

// AccountService provides account operations.
type AccountService struct{ t *transport }

func (s *AccountService) ExportAccountData(ctx context.Context) (*AccountExport, error) {
	return doJSON[AccountExport](s.t, ctx, "GET", "/v1/account/export", nil)
}

func (s *AccountService) GetOnboardingProgress(ctx context.Context, orgID string) (*OnboardingProgress, error) {
	return doJSON[OnboardingProgress](s.t, ctx, "GET", fmt.Sprintf("/v1/organizations/%s/onboarding", orgID), nil)
}

func (s *AccountService) UpdateOnboardingProgress(ctx context.Context, orgID string, body UpdateOnboardingRequest) (*OnboardingProgress, error) {
	return doJSON[OnboardingProgress](s.t, ctx, "PATCH", fmt.Sprintf("/v1/organizations/%s/onboarding", orgID), body)
}
