// Code generated by generate-sdk-go.ts — DO NOT EDIT.

package pgbeam

import (
	"context"
	"fmt"
)

var _ = fmt.Sprintf

// Client is the PgBeam API client. Access operations through service fields.
type Client struct {
	Projects   *ProjectsService
	Databases  *DatabasesService
	Policies   *PoliciesService
	Agents     *AgentsService
	Approvals  *ApprovalsService
	Webhooks   *WebhooksService
	Anomalies  *AnomaliesService
	Branches   *BranchesService
	Migrations *MigrationsService
	Analytics  *AnalyticsService
	Platform   *PlatformService
	Account    *AccountService
	t          *transport
}

// NewClient creates a new PgBeam API client.
func NewClient(opts *ClientOptions) *Client {
	t := newTransport(opts)
	c := &Client{t: t}
	c.Projects = &ProjectsService{t: t}
	c.Databases = &DatabasesService{t: t}
	c.Policies = &PoliciesService{t: t}
	c.Agents = &AgentsService{t: t}
	c.Approvals = &ApprovalsService{t: t}
	c.Webhooks = &WebhooksService{t: t}
	c.Anomalies = &AnomaliesService{t: t}
	c.Branches = &BranchesService{t: t}
	c.Migrations = &MigrationsService{t: t}
	c.Analytics = &AnalyticsService{t: t}
	c.Platform = &PlatformService{t: t}
	c.Account = &AccountService{t: t}
	return c
}

// ProjectsService provides projects operations.
type ProjectsService struct{ t *transport }

func (s *ProjectsService) ListCacheRules(ctx context.Context, projectID string, databaseID string, params *ListCacheRulesParams) (*ListCacheRulesResponse, error) {
	return doQuery[ListCacheRulesResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/databases/%s/cache-rules", projectID, databaseID), params)
}

func (s *ProjectsService) UpdateCacheRule(ctx context.Context, projectID string, databaseID string, queryHash string, body UpdateCacheRuleRequest) (*UpdateCacheRuleResponse, error) {
	return doJSON[UpdateCacheRuleResponse](s.t, ctx, "PUT", fmt.Sprintf("/v1/projects/%s/databases/%s/cache-rules/%s", projectID, databaseID, queryHash), body)
}

func (s *ProjectsService) ListCustomDomains(ctx context.Context, projectID string, params *ListCustomDomainsParams) (*ListCustomDomainsResponse, error) {
	return doQuery[ListCustomDomainsResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/domains", projectID), params)
}

func (s *ProjectsService) CreateCustomDomain(ctx context.Context, projectID string, body CreateCustomDomainRequest) (*CustomDomain, error) {
	return doJSON[CustomDomain](s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/domains", projectID), body)
}

func (s *ProjectsService) DeleteCustomDomain(ctx context.Context, projectID string, domainID string) error {
	return doVoid(s.t, ctx, "DELETE", fmt.Sprintf("/v1/projects/%s/domains/%s", projectID, domainID), nil)
}

func (s *ProjectsService) VerifyCustomDomain(ctx context.Context, projectID string, domainID string) (*VerifyCustomDomainResponse, error) {
	return doJSON[VerifyCustomDomainResponse](s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/domains/%s/verify", projectID, domainID), nil)
}

func (s *ProjectsService) ListProjects(ctx context.Context, params *ListProjectsParams) (*ListProjectsResponse, error) {
	return doQuery[ListProjectsResponse](s.t, ctx, "/v1/projects", params)
}

func (s *ProjectsService) CreateProject(ctx context.Context, body CreateProjectRequest) (*CreateProjectResponse, error) {
	return doJSON[CreateProjectResponse](s.t, ctx, "POST", "/v1/projects", body)
}

func (s *ProjectsService) GetProject(ctx context.Context, projectID string) (*Project, error) {
	return doJSON[Project](s.t, ctx, "GET", fmt.Sprintf("/v1/projects/%s", projectID), nil)
}

func (s *ProjectsService) UpdateProject(ctx context.Context, projectID string, body UpdateProjectRequest) (*Project, error) {
	return doJSON[Project](s.t, ctx, "PATCH", fmt.Sprintf("/v1/projects/%s", projectID), body)
}

func (s *ProjectsService) DeleteProject(ctx context.Context, projectID string) error {
	return doVoid(s.t, ctx, "DELETE", fmt.Sprintf("/v1/projects/%s", projectID), nil)
}

func (s *ProjectsService) GetProjectMetrics(ctx context.Context, projectID string, params *GetProjectMetricsParams) (*ProjectMetricsResponse, error) {
	return doQuery[ProjectMetricsResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/metrics", projectID), params)
}

func (s *ProjectsService) ListReplicas(ctx context.Context, databaseID string) (*ListReplicasResponse, error) {
	return doJSON[ListReplicasResponse](s.t, ctx, "GET", fmt.Sprintf("/v1/databases/%s/replicas", databaseID), nil)
}

func (s *ProjectsService) CreateReplica(ctx context.Context, databaseID string, body CreateReplicaRequest) (*Replica, error) {
	return doJSON[Replica](s.t, ctx, "POST", fmt.Sprintf("/v1/databases/%s/replicas", databaseID), body)
}

func (s *ProjectsService) DeleteReplica(ctx context.Context, databaseID string, replicaID string) error {
	return doVoid(s.t, ctx, "DELETE", fmt.Sprintf("/v1/databases/%s/replicas/%s", databaseID, replicaID), nil)
}

// DatabasesService provides databases operations.
type DatabasesService struct{ t *transport }

func (s *DatabasesService) ListDatabases(ctx context.Context, projectID string, params *ListDatabasesParams) (*ListDatabasesResponse, error) {
	return doQuery[ListDatabasesResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/databases", projectID), params)
}

func (s *DatabasesService) CreateDatabase(ctx context.Context, projectID string, body CreateDatabaseRequest) (*Database, error) {
	return doJSON[Database](s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/databases", projectID), body)
}

func (s *DatabasesService) GetDatabase(ctx context.Context, projectID string, databaseID string) (*Database, error) {
	return doJSON[Database](s.t, ctx, "GET", fmt.Sprintf("/v1/projects/%s/databases/%s", projectID, databaseID), nil)
}

func (s *DatabasesService) UpdateDatabase(ctx context.Context, projectID string, databaseID string, body UpdateDatabaseRequest) (*Database, error) {
	return doJSON[Database](s.t, ctx, "PATCH", fmt.Sprintf("/v1/projects/%s/databases/%s", projectID, databaseID), body)
}

func (s *DatabasesService) DeleteDatabase(ctx context.Context, projectID string, databaseID string) error {
	return doVoid(s.t, ctx, "DELETE", fmt.Sprintf("/v1/projects/%s/databases/%s", projectID, databaseID), nil)
}

func (s *DatabasesService) TestDatabaseConnection(ctx context.Context, projectID string, databaseID string) (*TestConnectionResult, error) {
	return doJSON[TestConnectionResult](s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/databases/%s/test-connection", projectID, databaseID), nil)
}

// PoliciesService provides policies operations.
type PoliciesService struct{ t *transport }

func (s *PoliciesService) ListPolicyProfiles(ctx context.Context, projectID string, params *ListPolicyProfilesParams) (*ListPolicyProfilesResponse, error) {
	return doQuery[ListPolicyProfilesResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/policies", projectID), params)
}

func (s *PoliciesService) CreatePolicyProfile(ctx context.Context, projectID string, body PolicyProfileInput) (*PolicyProfile, error) {
	return doJSON[PolicyProfile](s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/policies", projectID), body)
}

func (s *PoliciesService) GetPolicyProfile(ctx context.Context, projectID string, policyID string) (*PolicyProfile, error) {
	return doJSON[PolicyProfile](s.t, ctx, "GET", fmt.Sprintf("/v1/projects/%s/policies/%s", projectID, policyID), nil)
}

func (s *PoliciesService) UpdatePolicyProfile(ctx context.Context, projectID string, policyID string, body PolicyProfileInput) (*PolicyProfile, error) {
	return doJSON[PolicyProfile](s.t, ctx, "PUT", fmt.Sprintf("/v1/projects/%s/policies/%s", projectID, policyID), body)
}

func (s *PoliciesService) DeletePolicyProfile(ctx context.Context, projectID string, policyID string) error {
	return doVoid(s.t, ctx, "DELETE", fmt.Sprintf("/v1/projects/%s/policies/%s", projectID, policyID), nil)
}

// AgentsService provides agents operations.
type AgentsService struct{ t *transport }

func (s *AgentsService) ListAgentCredentials(ctx context.Context, projectID string, params *ListAgentCredentialsParams) (*ListAgentCredentialsResponse, error) {
	return doQuery[ListAgentCredentialsResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/agents", projectID), params)
}

func (s *AgentsService) CreateAgentCredential(ctx context.Context, projectID string, body CreateAgentCredentialRequest) (*AgentCredentialSecrets, error) {
	return doJSON[AgentCredentialSecrets](s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/agents", projectID), body)
}

func (s *AgentsService) GetAgentCredential(ctx context.Context, projectID string, agentID string) (*AgentCredential, error) {
	return doJSON[AgentCredential](s.t, ctx, "GET", fmt.Sprintf("/v1/projects/%s/agents/%s", projectID, agentID), nil)
}

func (s *AgentsService) UpdateAgentCredentialStatus(ctx context.Context, projectID string, agentID string, body UpdateAgentCredentialStatusRequest) (*AgentCredential, error) {
	return doJSON[AgentCredential](s.t, ctx, "PATCH", fmt.Sprintf("/v1/projects/%s/agents/%s", projectID, agentID), body)
}

func (s *AgentsService) RevokeAgentCredential(ctx context.Context, projectID string, agentID string) error {
	return doVoid(s.t, ctx, "DELETE", fmt.Sprintf("/v1/projects/%s/agents/%s", projectID, agentID), nil)
}

func (s *AgentsService) RotateAgentCredential(ctx context.Context, projectID string, agentID string) (*AgentCredentialSecrets, error) {
	return doJSON[AgentCredentialSecrets](s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/agents/%s/rotate", projectID, agentID), nil)
}

func (s *AgentsService) ListAuditLogs(ctx context.Context, projectID string, params *ListAuditLogsParams) (*ListAuditLogsResponse, error) {
	return doQuery[ListAuditLogsResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/audit-logs", projectID), params)
}

// ApprovalsService provides approvals operations.
type ApprovalsService struct{ t *transport }

func (s *ApprovalsService) ListApprovalRequests(ctx context.Context, projectID string, params *ListApprovalRequestsParams) (*ListApprovalRequestsResponse, error) {
	return doQuery[ListApprovalRequestsResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/approvals", projectID), params)
}

func (s *ApprovalsService) ApproveApprovalRequest(ctx context.Context, projectID string, approvalID string, body ApprovalDecisionRequest) (*ApprovalRequest, error) {
	return doJSON[ApprovalRequest](s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/approvals/%s/approve", projectID, approvalID), body)
}

func (s *ApprovalsService) RejectApprovalRequest(ctx context.Context, projectID string, approvalID string, body ApprovalDecisionRequest) (*ApprovalRequest, error) {
	return doJSON[ApprovalRequest](s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/approvals/%s/reject", projectID, approvalID), body)
}

// WebhooksService provides webhooks operations.
type WebhooksService struct{ t *transport }

func (s *WebhooksService) ListWebhookEndpoints(ctx context.Context, projectID string, params *ListWebhookEndpointsParams) (*ListWebhookEndpointsResponse, error) {
	return doQuery[ListWebhookEndpointsResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/webhooks", projectID), params)
}

func (s *WebhooksService) CreateWebhookEndpoint(ctx context.Context, projectID string, body WebhookEndpointInput) (*WebhookEndpoint, error) {
	return doJSON[WebhookEndpoint](s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/webhooks", projectID), body)
}

func (s *WebhooksService) GetWebhookEndpoint(ctx context.Context, projectID string, webhookID string) (*WebhookEndpoint, error) {
	return doJSON[WebhookEndpoint](s.t, ctx, "GET", fmt.Sprintf("/v1/projects/%s/webhooks/%s", projectID, webhookID), nil)
}

func (s *WebhooksService) UpdateWebhookEndpoint(ctx context.Context, projectID string, webhookID string, body WebhookEndpointInput) (*WebhookEndpoint, error) {
	return doJSON[WebhookEndpoint](s.t, ctx, "PUT", fmt.Sprintf("/v1/projects/%s/webhooks/%s", projectID, webhookID), body)
}

func (s *WebhooksService) DeleteWebhookEndpoint(ctx context.Context, projectID string, webhookID string) error {
	return doVoid(s.t, ctx, "DELETE", fmt.Sprintf("/v1/projects/%s/webhooks/%s", projectID, webhookID), nil)
}

func (s *WebhooksService) TestWebhookEndpoint(ctx context.Context, projectID string, webhookID string) error {
	return doVoid(s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/webhooks/%s/test", projectID, webhookID), nil)
}

// AnomaliesService provides anomalies operations.
type AnomaliesService struct{ t *transport }

func (s *AnomaliesService) ListAnomalyAlerts(ctx context.Context, projectID string, params *ListAnomalyAlertsParams) (*ListAnomalyAlertsResponse, error) {
	return doQuery[ListAnomalyAlertsResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/anomalies", projectID), params)
}

func (s *AnomaliesService) UpdateAnomalyAlert(ctx context.Context, projectID string, anomalyID string, body UpdateAnomalyAlertRequest) (*AnomalyAlert, error) {
	return doJSON[AnomalyAlert](s.t, ctx, "PATCH", fmt.Sprintf("/v1/projects/%s/anomalies/%s", projectID, anomalyID), body)
}

// BranchesService provides branches operations.
type BranchesService struct{ t *transport }

func (s *BranchesService) ListDatabaseBranches(ctx context.Context, projectID string, params *ListDatabaseBranchesParams) (*ListDatabaseBranchesResponse, error) {
	return doQuery[ListDatabaseBranchesResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/branches", projectID), params)
}

func (s *BranchesService) DiscardDatabaseBranch(ctx context.Context, projectID string, branchID string) error {
	return doVoid(s.t, ctx, "DELETE", fmt.Sprintf("/v1/projects/%s/branches/%s", projectID, branchID), nil)
}

// MigrationsService provides migrations operations.
type MigrationsService struct{ t *transport }

func (s *MigrationsService) LintMigration(ctx context.Context, projectID string, body MigrationLintRequest) (*MigrationLintResponse, error) {
	return doJSON[MigrationLintResponse](s.t, ctx, "POST", fmt.Sprintf("/v1/projects/%s/migrations:lint", projectID), body)
}

// AnalyticsService provides analytics operations.
type AnalyticsService struct{ t *transport }

func (s *AnalyticsService) ListPlans(ctx context.Context) (*ListPlansResponse, error) {
	return doJSON[ListPlansResponse](s.t, ctx, "GET", "/v1/plans", nil)
}

func (s *AnalyticsService) GetOrganizationPlan(ctx context.Context, orgID string) (*OrganizationPlan, error) {
	return doJSON[OrganizationPlan](s.t, ctx, "GET", fmt.Sprintf("/v1/organizations/%s/plan", orgID), nil)
}

func (s *AnalyticsService) UpdateSpendLimit(ctx context.Context, orgID string, body UpdateSpendLimitRequest) (*OrganizationPlan, error) {
	return doJSON[OrganizationPlan](s.t, ctx, "PUT", fmt.Sprintf("/v1/organizations/%s/spend-limit", orgID), body)
}

func (s *AnalyticsService) SubmitCancellationFeedback(ctx context.Context, orgID string, body CancellationFeedbackRequest) error {
	return doVoid(s.t, ctx, "POST", fmt.Sprintf("/v1/organizations/%s/cancellation-feedback", orgID), body)
}

func (s *AnalyticsService) GetProjectInsights(ctx context.Context, projectID string, params *GetProjectInsightsParams) (*ProjectInsights, error) {
	return doQuery[ProjectInsights](s.t, ctx, fmt.Sprintf("/v1/projects/%s/insights", projectID), params)
}

func (s *AnalyticsService) GetOrganizationUsage(ctx context.Context, orgID string, params *GetOrganizationUsageParams) (*UsageResponse, error) {
	return doQuery[UsageResponse](s.t, ctx, fmt.Sprintf("/v1/organizations/%s/usage", orgID), params)
}

func (s *AnalyticsService) GetProjectUsage(ctx context.Context, projectID string, params *GetProjectUsageParams) (*ProjectUsageResponse, error) {
	return doQuery[ProjectUsageResponse](s.t, ctx, fmt.Sprintf("/v1/projects/%s/usage", projectID), params)
}

// PlatformService provides platform operations.
type PlatformService struct{ t *transport }

func (s *PlatformService) GetHealth(ctx context.Context) (*HealthResponse, error) {
	return doJSON[HealthResponse](s.t, ctx, "GET", "/v1/health", nil)
}

func (s *PlatformService) ListRegions(ctx context.Context) (*ListRegionsResponse, error) {
	return doJSON[ListRegionsResponse](s.t, ctx, "GET", "/v1/regions", nil)
}

// AccountService provides account operations.
type AccountService struct{ t *transport }

func (s *AccountService) ExportAccountData(ctx context.Context) (*AccountExport, error) {
	return doJSON[AccountExport](s.t, ctx, "GET", "/v1/account/export", nil)
}

func (s *AccountService) GetOnboardingProgress(ctx context.Context, orgID string) (*OnboardingProgress, error) {
	return doJSON[OnboardingProgress](s.t, ctx, "GET", fmt.Sprintf("/v1/organizations/%s/onboarding", orgID), nil)
}

func (s *AccountService) UpdateOnboardingProgress(ctx context.Context, orgID string, body UpdateOnboardingRequest) (*OnboardingProgress, error) {
	return doJSON[OnboardingProgress](s.t, ctx, "PATCH", fmt.Sprintf("/v1/organizations/%s/onboarding", orgID), body)
}
