// Package pgbeam provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package pgbeam

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CacheRuleEntryQueryType.
const (
	Other CacheRuleEntryQueryType = "other"
	Read  CacheRuleEntryQueryType = "read"
	Write CacheRuleEntryQueryType = "write"
)

// Valid indicates whether the value is a known member of the CacheRuleEntryQueryType enum.
func (e CacheRuleEntryQueryType) Valid() bool {
	switch e {
	case Other:
		return true
	case Read:
		return true
	case Write:
		return true
	default:
		return false
	}
}

// Defines values for CacheRuleEntryRecommendation.
const (
	Fair  CacheRuleEntryRecommendation = "fair"
	Good  CacheRuleEntryRecommendation = "good"
	Great CacheRuleEntryRecommendation = "great"
	Poor  CacheRuleEntryRecommendation = "poor"
)

// Valid indicates whether the value is a known member of the CacheRuleEntryRecommendation enum.
func (e CacheRuleEntryRecommendation) Valid() bool {
	switch e {
	case Fair:
		return true
	case Good:
		return true
	case Great:
		return true
	case Poor:
		return true
	default:
		return false
	}
}

// Defines values for CreateProjectRequestCloud.
const (
	CreateProjectRequestCloudAws   CreateProjectRequestCloud = "aws"
	CreateProjectRequestCloudAzure CreateProjectRequestCloud = "azure"
	CreateProjectRequestCloudGcp   CreateProjectRequestCloud = "gcp"
)

// Valid indicates whether the value is a known member of the CreateProjectRequestCloud enum.
func (e CreateProjectRequestCloud) Valid() bool {
	switch e {
	case CreateProjectRequestCloudAws:
		return true
	case CreateProjectRequestCloudAzure:
		return true
	case CreateProjectRequestCloudGcp:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseRole.
const (
	DatabaseRolePrimary DatabaseRole = "primary"
	DatabaseRoleReplica DatabaseRole = "replica"
)

// Valid indicates whether the value is a known member of the DatabaseRole enum.
func (e DatabaseRole) Valid() bool {
	switch e {
	case DatabaseRolePrimary:
		return true
	case DatabaseRoleReplica:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Degraded HealthResponseStatus = "degraded"
	Ok       HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for McpRequestJsonrpc.
const (
	McpRequestJsonrpcN20 McpRequestJsonrpc = "2.0"
)

// Valid indicates whether the value is a known member of the McpRequestJsonrpc enum.
func (e McpRequestJsonrpc) Valid() bool {
	switch e {
	case McpRequestJsonrpcN20:
		return true
	default:
		return false
	}
}

// Defines values for McpRequestMethod.
const (
	Initialize               McpRequestMethod = "initialize"
	Notificationsinitialized McpRequestMethod = "notifications/initialized"
	Ping                     McpRequestMethod = "ping"
	Toolscall                McpRequestMethod = "tools/call"
	Toolslist                McpRequestMethod = "tools/list"
)

// Valid indicates whether the value is a known member of the McpRequestMethod enum.
func (e McpRequestMethod) Valid() bool {
	switch e {
	case Initialize:
		return true
	case Notificationsinitialized:
		return true
	case Ping:
		return true
	case Toolscall:
		return true
	case Toolslist:
		return true
	default:
		return false
	}
}

// Defines values for McpResponseJsonrpc.
const (
	McpResponseJsonrpcN20 McpResponseJsonrpc = "2.0"
)

// Valid indicates whether the value is a known member of the McpResponseJsonrpc enum.
func (e McpResponseJsonrpc) Valid() bool {
	switch e {
	case McpResponseJsonrpcN20:
		return true
	default:
		return false
	}
}

// Defines values for OrganizationPlanBillingProvider.
const (
	OrganizationPlanBillingProviderAws    OrganizationPlanBillingProvider = "aws"
	OrganizationPlanBillingProviderManual OrganizationPlanBillingProvider = "manual"
	OrganizationPlanBillingProviderStripe OrganizationPlanBillingProvider = "stripe"
	OrganizationPlanBillingProviderVercel OrganizationPlanBillingProvider = "vercel"
)

// Valid indicates whether the value is a known member of the OrganizationPlanBillingProvider enum.
func (e OrganizationPlanBillingProvider) Valid() bool {
	switch e {
	case OrganizationPlanBillingProviderAws:
		return true
	case OrganizationPlanBillingProviderManual:
		return true
	case OrganizationPlanBillingProviderStripe:
		return true
	case OrganizationPlanBillingProviderVercel:
		return true
	default:
		return false
	}
}

// Defines values for OrganizationPlanPlan.
const (
	Enterprise OrganizationPlanPlan = "enterprise"
	Pro        OrganizationPlanPlan = "pro"
	Scale      OrganizationPlanPlan = "scale"
	Starter    OrganizationPlanPlan = "starter"
)

// Valid indicates whether the value is a known member of the OrganizationPlanPlan enum.
func (e OrganizationPlanPlan) Valid() bool {
	switch e {
	case Enterprise:
		return true
	case Pro:
		return true
	case Scale:
		return true
	case Starter:
		return true
	default:
		return false
	}
}

// Defines values for OrganizationPlanSubscriptionStatus.
const (
	OrganizationPlanSubscriptionStatusActive            OrganizationPlanSubscriptionStatus = "active"
	OrganizationPlanSubscriptionStatusCanceled          OrganizationPlanSubscriptionStatus = "canceled"
	OrganizationPlanSubscriptionStatusIncomplete        OrganizationPlanSubscriptionStatus = "incomplete"
	OrganizationPlanSubscriptionStatusIncompleteExpired OrganizationPlanSubscriptionStatus = "incomplete_expired"
	OrganizationPlanSubscriptionStatusNone              OrganizationPlanSubscriptionStatus = "none"
	OrganizationPlanSubscriptionStatusPastDue           OrganizationPlanSubscriptionStatus = "past_due"
	OrganizationPlanSubscriptionStatusPaused            OrganizationPlanSubscriptionStatus = "paused"
	OrganizationPlanSubscriptionStatusTrialing          OrganizationPlanSubscriptionStatus = "trialing"
	OrganizationPlanSubscriptionStatusUnpaid            OrganizationPlanSubscriptionStatus = "unpaid"
)

// Valid indicates whether the value is a known member of the OrganizationPlanSubscriptionStatus enum.
func (e OrganizationPlanSubscriptionStatus) Valid() bool {
	switch e {
	case OrganizationPlanSubscriptionStatusActive:
		return true
	case OrganizationPlanSubscriptionStatusCanceled:
		return true
	case OrganizationPlanSubscriptionStatusIncomplete:
		return true
	case OrganizationPlanSubscriptionStatusIncompleteExpired:
		return true
	case OrganizationPlanSubscriptionStatusNone:
		return true
	case OrganizationPlanSubscriptionStatusPastDue:
		return true
	case OrganizationPlanSubscriptionStatusPaused:
		return true
	case OrganizationPlanSubscriptionStatusTrialing:
		return true
	case OrganizationPlanSubscriptionStatusUnpaid:
		return true
	default:
		return false
	}
}

// Defines values for PoolMode.
const (
	Session     PoolMode = "session"
	Statement   PoolMode = "statement"
	Transaction PoolMode = "transaction"
)

// Valid indicates whether the value is a known member of the PoolMode enum.
func (e PoolMode) Valid() bool {
	switch e {
	case Session:
		return true
	case Statement:
		return true
	case Transaction:
		return true
	default:
		return false
	}
}

// Defines values for ProjectCloud.
const (
	ProjectCloudAws   ProjectCloud = "aws"
	ProjectCloudAzure ProjectCloud = "azure"
	ProjectCloudGcp   ProjectCloud = "gcp"
)

// Valid indicates whether the value is a known member of the ProjectCloud enum.
func (e ProjectCloud) Valid() bool {
	switch e {
	case ProjectCloudAws:
		return true
	case ProjectCloudAzure:
		return true
	case ProjectCloudGcp:
		return true
	default:
		return false
	}
}

// Defines values for ProjectStatus.
const (
	ProjectStatusActive    ProjectStatus = "active"
	ProjectStatusDeleted   ProjectStatus = "deleted"
	ProjectStatusSuspended ProjectStatus = "suspended"
)

// Valid indicates whether the value is a known member of the ProjectStatus enum.
func (e ProjectStatus) Valid() bool {
	switch e {
	case ProjectStatusActive:
		return true
	case ProjectStatusDeleted:
		return true
	case ProjectStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for RegionProvider.
const (
	RegionProviderAws   RegionProvider = "aws"
	RegionProviderAzure RegionProvider = "azure"
	RegionProviderGcp   RegionProvider = "gcp"
)

// Valid indicates whether the value is a known member of the RegionProvider enum.
func (e RegionProvider) Valid() bool {
	switch e {
	case RegionProviderAws:
		return true
	case RegionProviderAzure:
		return true
	case RegionProviderGcp:
		return true
	default:
		return false
	}
}

// Defines values for RegionStatus.
const (
	Active   RegionStatus = "active"
	Draining RegionStatus = "draining"
	Inactive RegionStatus = "inactive"
)

// Valid indicates whether the value is a known member of the RegionStatus enum.
func (e RegionStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Draining:
		return true
	case Inactive:
		return true
	default:
		return false
	}
}

// Defines values for SSLMode.
const (
	Allow      SSLMode = "allow"
	Disable    SSLMode = "disable"
	Prefer     SSLMode = "prefer"
	Require    SSLMode = "require"
	VerifyCa   SSLMode = "verify-ca"
	VerifyFull SSLMode = "verify-full"
)

// Valid indicates whether the value is a known member of the SSLMode enum.
func (e SSLMode) Valid() bool {
	switch e {
	case Allow:
		return true
	case Disable:
		return true
	case Prefer:
		return true
	case Require:
		return true
	case VerifyCa:
		return true
	case VerifyFull:
		return true
	default:
		return false
	}
}

// Defines values for UpdateOnboardingRequestStep.
const (
	ConnectionStringCopied UpdateOnboardingRequestStep = "connection_string_copied"
	ConnectionTested       UpdateOnboardingRequestStep = "connection_tested"
	DatabaseAdded          UpdateOnboardingRequestStep = "database_added"
	FirstQueryRun          UpdateOnboardingRequestStep = "first_query_run"
	ProjectCreated         UpdateOnboardingRequestStep = "project_created"
)

// Valid indicates whether the value is a known member of the UpdateOnboardingRequestStep enum.
func (e UpdateOnboardingRequestStep) Valid() bool {
	switch e {
	case ConnectionStringCopied:
		return true
	case ConnectionTested:
		return true
	case DatabaseAdded:
		return true
	case FirstQueryRun:
		return true
	case ProjectCreated:
		return true
	default:
		return false
	}
}

// Defines values for ListProjectsParamsSortBy.
const (
	ActiveConnections ListProjectsParamsSortBy = "active_connections"
	CreatedAt         ListProjectsParamsSortBy = "created_at"
	Name              ListProjectsParamsSortBy = "name"
)

// Valid indicates whether the value is a known member of the ListProjectsParamsSortBy enum.
func (e ListProjectsParamsSortBy) Valid() bool {
	switch e {
	case ActiveConnections:
		return true
	case CreatedAt:
		return true
	case Name:
		return true
	default:
		return false
	}
}

// Defines values for GetProjectInsightsParamsRange.
const (
	N1h  GetProjectInsightsParamsRange = "1h"
	N24h GetProjectInsightsParamsRange = "24h"
	N6h  GetProjectInsightsParamsRange = "6h"
	N7d  GetProjectInsightsParamsRange = "7d"
)

// Valid indicates whether the value is a known member of the GetProjectInsightsParamsRange enum.
func (e GetProjectInsightsParamsRange) Valid() bool {
	switch e {
	case N1h:
		return true
	case N24h:
		return true
	case N6h:
		return true
	case N7d:
		return true
	default:
		return false
	}
}

// AccountExport Full account data export for privacy and data-portability requests.
type AccountExport struct {
	// AuditLogs Recent audit log entries associated with the account.
	AuditLogs []struct {
		// Action Action captured by the audit log entry.
		Action string `json:"action"`

		// CreatedAt When the audit log entry was recorded.
		CreatedAt time.Time `json:"created_at"`

		// Id Audit log entry identifier.
		Id string `json:"id"`

		// IpAddress IP address associated with the action, if known.
		IpAddress *string `json:"ip_address,omitempty"`

		// ResourceId Identifier of the affected resource.
		ResourceId *string `json:"resource_id,omitempty"`

		// ResourceType Type of resource affected by the action.
		ResourceType *string `json:"resource_type,omitempty"`
	} `json:"audit_logs"`

	// Consents Recorded legal-document acceptances for the user.
	Consents []struct {
		// AcceptedAt When the document was accepted.
		AcceptedAt time.Time `json:"accepted_at"`

		// DocumentType Legal document type accepted by the user.
		DocumentType string `json:"document_type"`

		// DocumentVersion Accepted document version.
		DocumentVersion string `json:"document_version"`

		// Id Consent record identifier.
		Id string `json:"id"`

		// IpAddress IP address captured when consent was recorded.
		IpAddress *string `json:"ip_address,omitempty"`
	} `json:"consents"`

	// Databases Databases registered under the exported projects.
	Databases []struct {
		// CreatedAt When the database registration was created.
		CreatedAt time.Time `json:"created_at"`

		// Host Upstream PostgreSQL host.
		Host string `json:"host"`

		// Id Database identifier.
		Id string `json:"id"`

		// Name Upstream PostgreSQL database name.
		Name string `json:"name"`

		// Port Upstream PostgreSQL port.
		Port int `json:"port"`

		// ProjectId Owning project identifier.
		ProjectId string `json:"project_id"`

		// Role Database role within the project.
		Role string `json:"role"`

		// SslMode PostgreSQL SSL mode in use for the database.
		SslMode string `json:"ssl_mode"`
	} `json:"databases"`

	// EmailPreferences User communication preferences.
	EmailPreferences struct {
		// MarketingEmails Whether marketing emails are enabled.
		MarketingEmails *bool `json:"marketing_emails,omitempty"`

		// UsageLimitAlerts Whether usage alert emails are enabled.
		UsageLimitAlerts *bool `json:"usage_limit_alerts,omitempty"`
	} `json:"email_preferences"`

	// ExportedAt When the export was generated.
	ExportedAt time.Time `json:"exported_at"`

	// Organizations Organizations the user belongs to.
	Organizations []struct {
		// CreatedAt When the organization membership was created.
		CreatedAt time.Time `json:"created_at"`

		// Id Organization identifier.
		Id string `json:"id"`

		// Name Organization display name.
		Name string `json:"name"`

		// Role User role within the organization.
		Role string `json:"role"`

		// Slug Organization slug used in URLs and routing.
		Slug string `json:"slug"`
	} `json:"organizations"`

	// Projects Projects owned through the user's organizations.
	Projects []struct {
		// CreatedAt When the project was created.
		CreatedAt time.Time `json:"created_at"`

		// Description Project description at export time.
		Description string `json:"description"`

		// Id Project identifier.
		Id string `json:"id"`

		// Name Project display name.
		Name string `json:"name"`

		// OrgId Owning organization identifier.
		OrgId string `json:"org_id"`

		// Status Project lifecycle status.
		Status string `json:"status"`
	} `json:"projects"`

	// Sessions Auth sessions associated with the user.
	Sessions []struct {
		// CreatedAt When the session was created.
		CreatedAt time.Time `json:"created_at"`

		// ExpiresAt When the session expires.
		ExpiresAt time.Time `json:"expires_at"`

		// Id Session identifier.
		Id string `json:"id"`

		// IpAddress IP address used to create the session, if known.
		IpAddress *string `json:"ip_address,omitempty"`

		// UserAgent User agent captured for the session, if known.
		UserAgent *string `json:"user_agent,omitempty"`
	} `json:"sessions"`

	// User Core user profile data.
	User struct {
		// CreatedAt When the user account was created.
		CreatedAt time.Time `json:"created_at"`

		// Email Primary account email address.
		Email openapi_types.Email `json:"email"`

		// EmailVerified Whether the email address has been verified.
		EmailVerified bool `json:"email_verified"`

		// Id User identifier.
		Id string `json:"id"`

		// Image Avatar image URL, if present.
		Image *string `json:"image,omitempty"`

		// Name Display name for the user.
		Name string `json:"name"`

		// UpdatedAt When the user profile was last updated.
		UpdatedAt time.Time `json:"updated_at"`
	} `json:"user"`
}

// CacheConfig Query cache configuration.
type CacheConfig struct {
	// Enabled Whether query caching is enabled. When false, all queries bypass the cache.
	Enabled bool `json:"enabled"`

	// MaxEntries Maximum number of cached query results.
	MaxEntries int `json:"max_entries"`

	// SwrSeconds Stale-while-revalidate window in seconds.
	SwrSeconds int `json:"swr_seconds"`

	// TtlSeconds Cache TTL in seconds for query results.
	TtlSeconds int `json:"ttl_seconds"`
}

// CacheRuleEntry Observed query shape and its cache recommendation for a database.
type CacheRuleEntry struct {
	// AvgLatencyMs Average query latency in milliseconds.
	AvgLatencyMs float64 `json:"avg_latency_ms"`

	// AvgResponseBytes Average response size in bytes.
	AvgResponseBytes int64 `json:"avg_response_bytes"`

	// CacheEnabled Whether caching is enabled for this query shape.
	CacheEnabled bool `json:"cache_enabled"`

	// CacheSwrSeconds SWR override in seconds. Null means use project default.
	CacheSwrSeconds *int `json:"cache_swr_seconds,omitempty"`

	// CacheTtlSeconds TTL override in seconds. Null means use project default.
	CacheTtlSeconds *int `json:"cache_ttl_seconds,omitempty"`

	// CallCount Total number of executions observed.
	CallCount int64 `json:"call_count"`

	// FirstSeenAt When this query was first observed.
	FirstSeenAt time.Time `json:"first_seen_at"`

	// LastSeenAt When this query was last observed.
	LastSeenAt time.Time `json:"last_seen_at"`

	// NormalizedSql SQL with literals replaced by $N placeholders.
	NormalizedSql string `json:"normalized_sql"`

	// P95LatencyMs 95th percentile latency in milliseconds.
	P95LatencyMs float64 `json:"p95_latency_ms"`

	// QueryHash xxhash64 hex of the normalized SQL.
	QueryHash string `json:"query_hash"`

	// QueryType Query classification.
	QueryType CacheRuleEntryQueryType `json:"query_type"`

	// Recommendation Cache recommendation based on frequency, latency, and stability.
	Recommendation CacheRuleEntryRecommendation `json:"recommendation"`

	// StabilityRate Response stability rate (0.0 to 1.0). Higher means more stable.
	StabilityRate float64 `json:"stability_rate"`
}

// CacheRuleEntryQueryType Query classification.
type CacheRuleEntryQueryType string

// CacheRuleEntryRecommendation Cache recommendation based on frequency, latency, and stability.
type CacheRuleEntryRecommendation string

// CacheSummary Aggregate cache performance metrics for the selected time range.
type CacheSummary struct {
	// HitRate Cache hit rate as a fraction (0.0 to 1.0).
	HitRate float64 `json:"hit_rate"`

	// TotalHits Total number of cache hits in the selected time range.
	TotalHits int64 `json:"total_hits"`

	// TotalMisses Total number of cache misses in the selected time range.
	TotalMisses int64 `json:"total_misses"`
}

// CancellationFeedbackRequest Request body for capturing cancellation feedback from a user.
type CancellationFeedbackRequest struct {
	// Feedback Free-text feedback from the user.
	Feedback *string `json:"feedback,omitempty"`

	// Reason Predefined cancellation reason.
	Reason *string `json:"reason,omitempty"`
}

// CidrEntry An IP filtering rule with a CIDR range and optional human-readable label.
type CidrEntry struct {
	// Cidr CIDR range in IPv4 (e.g. 203.0.113.0/24) or IPv6 (e.g. 2001:db8::/32) notation. A plain IP without prefix length defaults to /32 (IPv4) or /128 (IPv6).
	Cidr string `json:"cidr"`

	// Label Optional human-readable label for this CIDR entry (e.g. "Office", "VPC").
	Label *string `json:"label,omitempty"`
}

// CreateCustomDomainRequest Request body for attaching a custom domain to a project.
type CreateCustomDomainRequest struct {
	// Domain The custom domain name to add (e.g., db.example.com).
	Domain string `json:"domain"`
}

// CreateDatabaseRequest Request body for registering an upstream database.
type CreateDatabaseRequest struct {
	// AutoReadRouting Auto-route SELECT queries to read replicas.
	AutoReadRouting *bool `json:"auto_read_routing,omitempty"`

	// CacheConfig Query cache configuration.
	CacheConfig *CacheConfig `json:"cache_config,omitempty"`

	// Host PostgreSQL host.
	Host string `json:"host"`

	// Name PostgreSQL database name.
	Name string `json:"name"`

	// Password PostgreSQL password. Stored encrypted at rest.
	Password *string `json:"password,omitempty"`

	// PoolConfig Connection pool configuration.
	PoolConfig *PoolConfig `json:"pool_config,omitempty"`

	// PoolRegion Region where the connection pool is maintained (near the database). When set and different from the client's edge region, queries are relayed through the pool region's data plane. Empty means direct connection.
	PoolRegion *string `json:"pool_region,omitempty"`

	// Port PostgreSQL port.
	Port int `json:"port"`

	// QueryTimeoutMs Query timeout in milliseconds. 0 means disabled (default).
	QueryTimeoutMs *int `json:"query_timeout_ms,omitempty"`

	// Role Database role. Primary receives writes, replicas receive reads.
	Role *DatabaseRole `json:"role,omitempty"`

	// SslMode PostgreSQL SSL connection mode.
	SslMode *SSLMode `json:"ssl_mode,omitempty"`

	// Username PostgreSQL username.
	Username string `json:"username"`
}

// CreateProjectRequest Request body for creating a project and its primary database.
type CreateProjectRequest struct {
	// Cloud Cloud provider for the project.
	Cloud *CreateProjectRequestCloud `json:"cloud,omitempty"`

	// Database Request body for registering an upstream database.
	Database CreateDatabaseRequest `json:"database"`

	// Description Optional project description.
	Description *string `json:"description,omitempty"`

	// Name Human-readable project name.
	Name string `json:"name"`

	// OrgId Better Auth organization ID.
	OrgId string `json:"org_id"`

	// Tags User-defined labels to attach to the project.
	Tags *[]string `json:"tags,omitempty"`
}

// CreateProjectRequestCloud Cloud provider for the project.
type CreateProjectRequestCloud string

// CreateProjectResponse Response returned after creating a project and its primary database.
type CreateProjectResponse struct {
	// Database Registered upstream PostgreSQL database for a project.
	Database *Database `json:"database,omitempty"`

	// Project Project configuration and current control-plane state.
	Project Project `json:"project"`
}

// CreateReplicaRequest Request body for adding a read replica to a database.
type CreateReplicaRequest struct {
	// Host PostgreSQL replica host.
	Host string `json:"host"`

	// Port PostgreSQL replica port.
	Port int `json:"port"`

	// SslMode PostgreSQL SSL connection mode.
	SslMode *SSLMode `json:"ssl_mode,omitempty"`
}

// CustomDomain Custom database hostname attached to a project.
type CustomDomain struct {
	// CreatedAt When the custom domain was created.
	CreatedAt time.Time `json:"created_at"`

	// DnsInstructions DNS records the user needs to create for domain verification.
	DnsInstructions *DnsInstructions `json:"dns_instructions,omitempty"`

	// DnsVerificationToken Token value for the DNS TXT record verification.
	DnsVerificationToken string `json:"dns_verification_token"`

	// Domain The custom domain name.
	Domain string `json:"domain"`

	// Id Unique domain identifier (prefixed).
	Id string `json:"id"`

	// ProjectId Owning project ID.
	ProjectId string `json:"project_id"`

	// TlsCertExpiry When the TLS certificate expires.
	TlsCertExpiry *time.Time `json:"tls_cert_expiry,omitempty"`

	// UpdatedAt When the custom domain was last updated.
	UpdatedAt time.Time `json:"updated_at"`

	// Verified Whether DNS ownership has been verified.
	Verified bool `json:"verified"`

	// VerifiedAt When DNS verification was completed.
	VerifiedAt *time.Time `json:"verified_at,omitempty"`
}

// DailyUsage Daily usage totals aggregated across all projects in an organization.
type DailyUsage struct {
	// BytesTransferred Total bytes transferred to clients.
	BytesTransferred int64 `json:"bytes_transferred"`

	// CacheHits Total cache hits on the day.
	CacheHits int64 `json:"cache_hits"`

	// CacheMisses Total cache misses on the day.
	CacheMisses int64 `json:"cache_misses"`

	// ConnectionSeconds Total proxy connection time consumed on the day.
	ConnectionSeconds int64 `json:"connection_seconds"`

	// Day Usage date in UTC.
	Day openapi_types.Date `json:"day"`

	// QueriesTotal Total queries served on the day.
	QueriesTotal int64 `json:"queries_total"`
}

// Database Registered upstream PostgreSQL database for a project.
type Database struct {
	// AutoReadRouting When enabled and replicas are configured, SELECT queries automatically route to read replicas without requiring the @pgbeam:replica SQL annotation.
	AutoReadRouting *bool `json:"auto_read_routing,omitempty"`

	// CacheConfig Query cache configuration.
	CacheConfig CacheConfig `json:"cache_config"`

	// ConnectionString Connection string for connecting through PgBeam proxy. Password is replaced with a placeholder.
	ConnectionString *string `json:"connection_string,omitempty"`

	// CreatedAt When the database registration was created.
	CreatedAt time.Time `json:"created_at"`

	// Host PostgreSQL host.
	Host string `json:"host"`

	// Id Unique database identifier (prefixed).
	Id string `json:"id"`

	// Name PostgreSQL database name.
	Name string `json:"name"`

	// PoolConfig Connection pool configuration.
	PoolConfig PoolConfig `json:"pool_config"`

	// PoolRegion Region where the connection pool is maintained (near the database). When set and different from the client's edge region, queries are relayed through the pool region's data plane. Empty means direct connection.
	PoolRegion *string `json:"pool_region,omitempty"`

	// Port PostgreSQL port.
	Port int `json:"port"`

	// ProjectId Owning project ID.
	ProjectId string `json:"project_id"`

	// QueryTimeoutMs Query timeout in milliseconds. When set (> 0), the proxy sends SET statement_timeout on upstream connections. 0 means disabled (default).
	QueryTimeoutMs *int `json:"query_timeout_ms,omitempty"`

	// Role Database role. Primary receives writes, replicas receive reads.
	Role *DatabaseRole `json:"role,omitempty"`

	// SslMode PostgreSQL SSL connection mode.
	SslMode SSLMode `json:"ssl_mode"`

	// UpdatedAt When the database registration was last updated.
	UpdatedAt time.Time `json:"updated_at"`

	// Username PostgreSQL username.
	Username string `json:"username"`
}

// DatabaseRole Database role. Primary receives writes, replicas receive reads.
type DatabaseRole string

// DnsInstructions DNS records the user needs to create for domain verification.
type DnsInstructions struct {
	// AcmeCnameHost The CNAME record host for ACME TLS certificate issuance.
	AcmeCnameHost *string `json:"acme_cname_host,omitempty"`

	// AcmeCnameTarget The CNAME target for ACME challenge delegation.
	AcmeCnameTarget *string `json:"acme_cname_target,omitempty"`

	// CnameHost The CNAME record host.
	CnameHost *string `json:"cname_host,omitempty"`

	// CnameTarget The CNAME record target.
	CnameTarget *string `json:"cname_target,omitempty"`

	// TxtHost The TXT record host for verification.
	TxtHost *string `json:"txt_host,omitempty"`

	// TxtValue The TXT record value for verification.
	TxtValue *string `json:"txt_value,omitempty"`
}

// Error Standard error response envelope for PgBeam API requests.
type Error struct {
	// Error Error metadata for the failed request.
	Error struct {
		// Code Machine-readable error code.
		Code string `json:"code"`

		// Message Human-readable error message.
		Message string `json:"message"`
	} `json:"error"`
}

// HealthResponse Health status and build metadata for the API service.
type HealthResponse struct {
	// ImageSha Resolved image SHA (digest or SHA tag).
	ImageSha string `json:"image_sha"`

	// Status Overall service health.
	Status HealthResponseStatus `json:"status"`

	// Timestamp Server time.
	Timestamp *time.Time `json:"timestamp,omitempty"`

	// Version API server version.
	Version string `json:"version"`
}

// HealthResponseStatus Overall service health.
type HealthResponseStatus string

// LatencySummary Aggregate latency metrics for the selected time range.
type LatencySummary struct {
	// AvgMs Average latency in milliseconds across all queries.
	AvgMs float64 `json:"avg_ms"`

	// P99Ms P99 latency in milliseconds across all queries.
	P99Ms float64 `json:"p99_ms"`
}

// ListCacheRulesResponse Cursor-paginated cache-rule entries for a database.
type ListCacheRulesResponse struct {
	// Entries Query shapes returned for the current page.
	Entries []CacheRuleEntry `json:"entries"`

	// NextPageToken Opaque token for cursor-based pagination.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// ListCustomDomainsResponse Cursor-paginated list of custom domains for a project.
type ListCustomDomainsResponse struct {
	// Domains Custom domains on the current page.
	Domains []CustomDomain `json:"domains"`

	// NextPageToken Token for the next page. Empty if no more results.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// ListDatabasesResponse Cursor-paginated list of databases attached to a project.
type ListDatabasesResponse struct {
	// Databases Databases on the current page.
	Databases []Database `json:"databases"`

	// NextPageToken Token for the next page. Empty if no more results.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// ListPlansResponse Response envelope for listing available billing plans.
type ListPlansResponse struct {
	// Plans Billing plans available for self-serve signups.
	Plans []PlanInfo `json:"plans"`
}

// ListProjectsResponse Cursor-paginated list of projects for an organization.
type ListProjectsResponse struct {
	// NextPageToken Token for the next page. Empty if no more results.
	NextPageToken *string `json:"next_page_token,omitempty"`

	// Projects Projects on the current page.
	Projects []Project `json:"projects"`

	// Total Total number of projects (across all pages).
	Total int `json:"total"`
}

// ListRegionsResponse Response envelope for available region queries.
type ListRegionsResponse struct {
	// Regions Regions currently known to the control plane.
	Regions []Region `json:"regions"`
}

// ListReplicasResponse Response envelope for listing registered replicas.
type ListReplicasResponse struct {
	// NextPageToken Opaque token for cursor-based pagination.
	NextPageToken *string `json:"next_page_token,omitempty"`

	// Replicas Read replicas attached to the database.
	Replicas []Replica `json:"replicas"`
}

// McpRequest JSON-RPC 2.0 request envelope for MCP over Streamable HTTP.
type McpRequest struct {
	// Id Request identifier. Omit for notifications.
	Id *string `json:"id,omitempty"`

	// Jsonrpc JSON-RPC version. Must be "2.0".
	Jsonrpc McpRequestJsonrpc `json:"jsonrpc"`

	// Method MCP method to invoke.
	Method McpRequestMethod `json:"method"`

	// Params Method-specific parameters.
	Params *map[string]interface{} `json:"params,omitempty"`
}

// McpRequestJsonrpc JSON-RPC version. Must be "2.0".
type McpRequestJsonrpc string

// McpRequestMethod MCP method to invoke.
type McpRequestMethod string

// McpResponse JSON-RPC 2.0 response envelope for MCP over Streamable HTTP.
type McpResponse struct {
	// Error JSON-RPC error (present on failure).
	Error *struct {
		// Code JSON-RPC error code.
		Code *int `json:"code,omitempty"`

		// Message Human-readable error message.
		Message *string `json:"message,omitempty"`
	} `json:"error,omitempty"`

	// Id Mirrors the request id. Null for parse errors.
	Id *string `json:"id"`

	// Jsonrpc JSON-RPC version. Always "2.0".
	Jsonrpc McpResponseJsonrpc `json:"jsonrpc"`

	// Result Method-specific result (present on success).
	Result *map[string]interface{} `json:"result,omitempty"`
}

// McpResponseJsonrpc JSON-RPC version. Always "2.0".
type McpResponseJsonrpc string

// MetricsSnapshot Aggregated project metrics captured for a point in time.
type MetricsSnapshot struct {
	// ActiveConnections Current active proxy connections.
	ActiveConnections int `json:"active_connections"`

	// AvgConnectMs Average upstream connection acquisition latency in milliseconds.
	AvgConnectMs *float64 `json:"avg_connect_ms,omitempty"`

	// AvgLatencyMs Average end-to-end query latency in milliseconds.
	AvgLatencyMs float64 `json:"avg_latency_ms"`

	// AvgQueryMs Average upstream query execution latency in milliseconds.
	AvgQueryMs *float64 `json:"avg_query_ms,omitempty"`

	// CacheHits Number of queries served from cache.
	CacheHits int64 `json:"cache_hits"`

	// CacheMisses Number of queries forwarded upstream.
	CacheMisses int64 `json:"cache_misses"`

	// CreatedAt When the snapshot was recorded.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique metrics snapshot identifier.
	Id string `json:"id"`

	// P99LatencyMs 99th percentile end-to-end query latency in milliseconds.
	P99LatencyMs float64 `json:"p99_latency_ms"`

	// ProjectId Project that produced the metrics snapshot.
	ProjectId string `json:"project_id"`

	// QueriesTotal Total queries served during the snapshot interval.
	QueriesTotal int64 `json:"queries_total"`

	// Region Region where the traffic was served.
	Region string `json:"region"`
}

// OnboardingProgress Progress state for the dashboard onboarding checklist.
type OnboardingProgress struct {
	// Completed Whether all onboarding steps are complete.
	Completed bool `json:"completed"`

	// CompletedAt When onboarding was completed. Null if not yet completed.
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	// ConnectionStringCopied Whether the connection string has been copied.
	ConnectionStringCopied bool `json:"connection_string_copied"`

	// ConnectionTested Whether the database connection has been tested.
	ConnectionTested bool `json:"connection_tested"`

	// DatabaseAdded Whether a database has been added.
	DatabaseAdded bool `json:"database_added"`

	// Dismissed Whether the user has dismissed the onboarding checklist.
	Dismissed bool `json:"dismissed"`

	// FirstQueryRun Whether the first query has been run through PgBeam.
	FirstQueryRun bool `json:"first_query_run"`

	// OrgCreated Whether the organization has been created.
	OrgCreated bool `json:"org_created"`

	// OrganizationId Organization ID this onboarding belongs to.
	OrganizationId string `json:"organization_id"`

	// ProjectCreated Whether a project has been created.
	ProjectCreated bool `json:"project_created"`

	// StepsCompleted Number of completed onboarding steps.
	StepsCompleted int `json:"steps_completed"`

	// StepsTotal Total number of onboarding steps.
	StepsTotal int `json:"steps_total"`
}

// OrganizationPlan Billing state and plan limits for an organization.
type OrganizationPlan struct {
	// BillingProvider Which billing provider manages this organization's subscription.
	BillingProvider *OrganizationPlanBillingProvider `json:"billing_provider,omitempty"`

	// CreatedAt When the billing record was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// CurrentPeriodEnd End of current billing period.
	CurrentPeriodEnd *time.Time `json:"current_period_end,omitempty"`

	// CustomPricing Whether the organization has custom enterprise pricing.
	CustomPricing *bool `json:"custom_pricing,omitempty"`

	// Enabled Whether the organization billing is active (false = suspended).
	Enabled *bool `json:"enabled,omitempty"`

	// Limits Effective usage limits enforced for an organization plan.
	Limits PlanLimits `json:"limits"`

	// OrgId Organization identifier the plan applies to.
	OrgId string `json:"org_id"`

	// Plan Current plan tier.
	Plan OrganizationPlanPlan `json:"plan"`

	// SpendLimit Monthly spend limit in dollars. Null means no limit.
	SpendLimit *float64 `json:"spend_limit,omitempty"`

	// SubscriptionStatus Stripe subscription status.
	SubscriptionStatus *OrganizationPlanSubscriptionStatus `json:"subscription_status,omitempty"`

	// UpdatedAt When the billing record was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// OrganizationPlanBillingProvider Which billing provider manages this organization's subscription.
type OrganizationPlanBillingProvider string

// OrganizationPlanPlan Current plan tier.
type OrganizationPlanPlan string

// OrganizationPlanSubscriptionStatus Stripe subscription status.
type OrganizationPlanSubscriptionStatus string

// PlanInfo Publicly visible plan metadata and limits.
type PlanInfo struct {
	// AnnualPrice Annual price in dollars (if applicable).
	AnnualPrice *int `json:"annual_price,omitempty"`

	// Description Short description of the plan.
	Description *string `json:"description,omitempty"`

	// Label Display label for the plan.
	Label string `json:"label"`

	// Limits Effective usage limits enforced for an organization plan.
	Limits PlanLimits `json:"limits"`

	// MonthlyPrice Monthly price in dollars.
	MonthlyPrice int `json:"monthly_price"`

	// Name Plan tier name (starter, pro, scale).
	Name string `json:"name"`

	// OverageText Human-readable overage pricing text.
	OverageText *string `json:"overage_text,omitempty"`

	// TrialDays Number of trial days for new signups.
	TrialDays *int `json:"trial_days,omitempty"`
}

// PlanLimits Effective usage limits enforced for an organization plan.
type PlanLimits struct {
	// BytesPerMonth Monthly data transfer quota in bytes. 0 means unlimited.
	BytesPerMonth int64 `json:"bytes_per_month"`

	// IncludedSeats Number of seats included in the plan.
	IncludedSeats int `json:"included_seats"`

	// MaxConnections Maximum concurrent connections per project.
	MaxConnections int `json:"max_connections"`

	// MaxDatabases Maximum databases per project.
	MaxDatabases int `json:"max_databases"`

	// MaxProjects Maximum number of active projects.
	MaxProjects int `json:"max_projects"`

	// MaxQueryShapes Maximum query shapes in cache rules. 0 means unlimited.
	MaxQueryShapes int `json:"max_query_shapes"`

	// QueriesPerDay Maximum queries per day across all projects. 0 means unlimited.
	QueriesPerDay int64 `json:"queries_per_day"`

	// QueriesPerSecond Maximum queries per second per project.
	QueriesPerSecond int `json:"queries_per_second"`
}

// PoolConfig Connection pool configuration.
type PoolConfig struct {
	// MaxActive Maximum concurrent upstream connections per pool.
	MaxActive *int `json:"max_active,omitempty"`

	// MinPoolSize Minimum idle connections maintained.
	MinPoolSize int `json:"min_pool_size"`

	// PoolMode Connection pool mode.
	PoolMode PoolMode `json:"pool_mode"`

	// PoolSize Maximum connections in the pool.
	PoolSize int `json:"pool_size"`
}

// PoolMode Connection pool mode.
type PoolMode string

// Project Project configuration and current control-plane state.
type Project struct {
	// ActiveConnections Current active connections (latest metrics snapshot). 0 when no metrics data.
	ActiveConnections *int `json:"active_connections,omitempty"`

	// AllowedCidrs IP filtering rules as CIDR ranges with optional labels. When non-empty, only connections from matching IPs are accepted. Empty array means all IPs are allowed (default). Both IPv4 (e.g. 10.0.0.0/8) and IPv6 (e.g. 2001:db8::/32) are supported.
	AllowedCidrs *[]CidrEntry `json:"allowed_cidrs,omitempty"`

	// BurstSize Burst allowance above the steady-state rate. 0 uses queries_per_second as burst.
	BurstSize *int32 `json:"burst_size,omitempty"`

	// Cloud Cloud provider where the project runs.
	Cloud *ProjectCloud `json:"cloud,omitempty"`

	// CreatedAt When the project was created.
	CreatedAt time.Time `json:"created_at"`

	// DatabaseCount Number of databases attached to this project.
	DatabaseCount *int `json:"database_count,omitempty"`

	// Description Optional project description.
	Description *string `json:"description,omitempty"`

	// Id Unique project identifier (prefixed).
	Id string `json:"id"`

	// MaxConnections Maximum concurrent proxy connections. 0 means unlimited.
	MaxConnections *int32 `json:"max_connections,omitempty"`

	// Name Human-readable project name.
	Name string `json:"name"`

	// OrgId Better Auth organization ID that owns this project.
	OrgId string `json:"org_id"`

	// ProxyHost Proxy hostname for connecting through PgBeam (e.g., myproject.aws.pgbeam.app).
	ProxyHost *string `json:"proxy_host,omitempty"`

	// QueriesPerSecond Maximum queries per second for this project. 0 means unlimited.
	QueriesPerSecond *int32 `json:"queries_per_second,omitempty"`

	// Status Project lifecycle status.
	Status ProjectStatus `json:"status"`

	// Tags User-defined labels applied to the project.
	Tags *[]string `json:"tags,omitempty"`

	// UpdatedAt When the project was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ProjectCloud Cloud provider where the project runs.
type ProjectCloud string

// ProjectDailyUsage Daily usage totals for a single project and region.
type ProjectDailyUsage struct {
	// BytesTransferred Total bytes transferred to clients.
	BytesTransferred int64 `json:"bytes_transferred"`

	// CacheHits Total cache hits on the day.
	CacheHits int64 `json:"cache_hits"`

	// CacheMisses Total cache misses on the day.
	CacheMisses int64 `json:"cache_misses"`

	// ConnectionSeconds Total proxy connection time consumed on the day.
	ConnectionSeconds int64 `json:"connection_seconds"`

	// Day Usage date in UTC.
	Day openapi_types.Date `json:"day"`

	// QueriesTotal Total queries served on the day.
	QueriesTotal int64 `json:"queries_total"`

	// Region Region where the traffic was served.
	Region string `json:"region"`
}

// ProjectInsights Query insights, cache performance, and latency for a project.
type ProjectInsights struct {
	// Cache Aggregate cache performance metrics for the selected time range.
	Cache CacheSummary `json:"cache"`

	// Latency Aggregate latency metrics for the selected time range.
	Latency LatencySummary `json:"latency"`

	// Queries Top query shapes observed for the project.
	Queries []QueryInsight `json:"queries"`
}

// ProjectMetricsResponse Response envelope for recent project metrics snapshots.
type ProjectMetricsResponse struct {
	// Snapshots Metrics snapshots ordered from newest to oldest.
	Snapshots []MetricsSnapshot `json:"snapshots"`
}

// ProjectStatus Project lifecycle status.
type ProjectStatus string

// ProjectUsageResponse Response envelope for project usage queries.
type ProjectUsageResponse struct {
	// Usage Daily usage entries grouped by region for the project.
	Usage []ProjectDailyUsage `json:"usage"`
}

// QueryInsight Aggregated analytics for a normalized SQL query shape.
type QueryInsight struct {
	// AvgLatencyMs Average query latency in milliseconds.
	AvgLatencyMs float64 `json:"avg_latency_ms"`

	// P99LatencyMs P99 query latency in milliseconds.
	P99LatencyMs float64 `json:"p99_latency_ms"`

	// QueryHash xxhash64 of the normalized SQL pattern (hex).
	QueryHash string `json:"query_hash"`

	// QueryPattern Normalized SQL pattern (truncated to 500 chars).
	QueryPattern string `json:"query_pattern"`

	// TotalCacheHits Total cache hits attributed to the query shape.
	TotalCacheHits int64 `json:"total_cache_hits"`

	// TotalCacheMisses Total cache misses attributed to the query shape.
	TotalCacheMisses int64 `json:"total_cache_misses"`

	// TotalCount Total number of executions in the time range.
	TotalCount int64 `json:"total_count"`
}

// Region Data plane region available for PgBeam traffic.
type Region struct {
	// Available Whether new projects can currently be assigned to the region.
	Available bool `json:"available"`

	// Continent Continent where the region is located.
	Continent *string `json:"continent,omitempty"`

	// Country Country where the region is located.
	Country *string `json:"country,omitempty"`

	// Id Region identifier (e.g. us-east-1).
	Id string `json:"id"`

	// Name Human-readable region name.
	Name string `json:"name"`

	// Provider Cloud provider.
	Provider RegionProvider `json:"provider"`

	// Status Region operational status.
	Status RegionStatus `json:"status"`
}

// RegionProvider Cloud provider.
type RegionProvider string

// RegionStatus Region operational status.
type RegionStatus string

// Replica Read replica registered for a primary database.
type Replica struct {
	// CreatedAt When the replica was created.
	CreatedAt time.Time `json:"created_at"`

	// DatabaseId Parent database ID.
	DatabaseId string `json:"database_id"`

	// Host PostgreSQL replica host.
	Host string `json:"host"`

	// Id Unique replica identifier (prefixed).
	Id string `json:"id"`

	// Port PostgreSQL replica port.
	Port int `json:"port"`

	// SslMode PostgreSQL SSL connection mode.
	SslMode SSLMode `json:"ssl_mode"`

	// UpdatedAt When the replica was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// SSLMode PostgreSQL SSL connection mode.
type SSLMode string

// TestConnectionResult Result of testing connectivity to an upstream database.
type TestConnectionResult struct {
	// Error Error message if the connection test failed.
	Error *string `json:"error,omitempty"`

	// LatencyMs Round-trip connection time in milliseconds.
	LatencyMs *float32 `json:"latency_ms,omitempty"`

	// Ok Whether the connection test succeeded.
	Ok bool `json:"ok"`

	// ServerVersion PostgreSQL server version string, if available.
	ServerVersion *string `json:"server_version,omitempty"`
}

// UpdateCacheRuleRequest Request body for updating cache behavior of a query shape.
type UpdateCacheRuleRequest struct {
	// CacheEnabled Whether to enable caching for this query shape.
	CacheEnabled bool `json:"cache_enabled"`

	// CacheSwrSeconds SWR override in seconds. Null to use project default.
	CacheSwrSeconds *int `json:"cache_swr_seconds,omitempty"`

	// CacheTtlSeconds TTL override in seconds. Null to use project default.
	CacheTtlSeconds *int `json:"cache_ttl_seconds,omitempty"`
}

// UpdateCacheRuleResponse Response returned after updating a cache rule.
type UpdateCacheRuleResponse struct {
	// Entry Observed query shape and its cache recommendation for a database.
	Entry CacheRuleEntry `json:"entry"`
}

// UpdateDatabaseRequest Request body for partially updating an upstream database.
type UpdateDatabaseRequest struct {
	// AutoReadRouting Auto-route SELECT queries to read replicas.
	AutoReadRouting *bool `json:"auto_read_routing,omitempty"`

	// CacheConfig Query cache configuration.
	CacheConfig *CacheConfig `json:"cache_config,omitempty"`

	// Host Updated PostgreSQL host.
	Host *string `json:"host,omitempty"`

	// Name Updated PostgreSQL database name.
	Name *string `json:"name,omitempty"`

	// Password Updated PostgreSQL password.
	Password *string `json:"password,omitempty"`

	// PoolConfig Connection pool configuration.
	PoolConfig *PoolConfig `json:"pool_config,omitempty"`

	// PoolRegion Region where the connection pool is maintained (near the database). When set and different from the client's edge region, queries are relayed through the pool region's data plane. Empty means direct connection.
	PoolRegion *string `json:"pool_region,omitempty"`

	// Port Updated PostgreSQL port.
	Port *int `json:"port,omitempty"`

	// QueryTimeoutMs Query timeout in milliseconds. 0 means disabled.
	QueryTimeoutMs *int `json:"query_timeout_ms,omitempty"`

	// Role Database role. Primary receives writes, replicas receive reads.
	Role *DatabaseRole `json:"role,omitempty"`

	// SslMode PostgreSQL SSL connection mode.
	SslMode *SSLMode `json:"ssl_mode,omitempty"`

	// Username Updated PostgreSQL username.
	Username *string `json:"username,omitempty"`
}

// UpdateOnboardingRequest Request body for advancing or dismissing onboarding.
type UpdateOnboardingRequest struct {
	// Dismiss Set to true to dismiss the onboarding checklist.
	Dismiss *bool `json:"dismiss,omitempty"`

	// Step The onboarding step to mark as complete.
	Step *UpdateOnboardingRequestStep `json:"step,omitempty"`
}

// UpdateOnboardingRequestStep The onboarding step to mark as complete.
type UpdateOnboardingRequestStep string

// UpdateProjectRequest Request body for partially updating a project.
type UpdateProjectRequest struct {
	// AllowedCidrs IP filtering rules as CIDR ranges with optional labels. Empty array means allow all. Both IPv4 and IPv6 CIDR notation are supported.
	AllowedCidrs *[]CidrEntry `json:"allowed_cidrs,omitempty"`

	// Description Updated project description.
	Description *string `json:"description,omitempty"`

	// Name Updated project name.
	Name *string `json:"name,omitempty"`

	// Status Project lifecycle status.
	Status *ProjectStatus `json:"status,omitempty"`

	// Tags Replacement set of user-defined project labels.
	Tags *[]string `json:"tags,omitempty"`
}

// UpdateSpendLimitRequest Request body for updating an organization's monthly spend cap.
type UpdateSpendLimitRequest struct {
	// SpendLimit Monthly spend limit in dollars. Null to remove the limit.
	SpendLimit *float64 `json:"spend_limit,omitempty"`
}

// UsageResponse Response envelope for organization usage queries.
type UsageResponse struct {
	// Usage Daily usage entries aggregated across the organization.
	Usage []DailyUsage `json:"usage"`
}

// VerifyCustomDomainResponse Result of checking DNS ownership for a custom domain.
type VerifyCustomDomainResponse struct {
	// Domain Custom database hostname attached to a project.
	Domain *CustomDomain `json:"domain,omitempty"`

	// Error Error message if verification failed.
	Error *string `json:"error,omitempty"`

	// Verified Whether DNS verification succeeded.
	Verified bool `json:"verified"`
}

// DatabaseId defines model for DatabaseId.
type DatabaseId = string

// DomainId defines model for DomainId.
type DomainId = string

// OrgId defines model for OrgId.
type OrgId = string

// PageSize defines model for PageSize.
type PageSize = int

// PageToken defines model for PageToken.
type PageToken = string

// ProjectId defines model for ProjectId.
type ProjectId = string

// ReplicaId defines model for ReplicaId.
type ReplicaId = string

// BadRequest Standard error response envelope for PgBeam API requests.
type BadRequest = Error

// Conflict Standard error response envelope for PgBeam API requests.
type Conflict = Error

// Forbidden Standard error response envelope for PgBeam API requests.
type Forbidden = Error

// NotFound Standard error response envelope for PgBeam API requests.
type NotFound = Error

// TooManyRequests Standard error response envelope for PgBeam API requests.
type TooManyRequests = Error

// Unauthorized Standard error response envelope for PgBeam API requests.
type Unauthorized = Error

// GetOrganizationUsageParams defines parameters for GetOrganizationUsage.
type GetOrganizationUsageParams struct {
	// StartDate Start date (inclusive, YYYY-MM-DD).
	StartDate openapi_types.Date `form:"start_date" json:"start_date"`

	// EndDate End date (inclusive, YYYY-MM-DD).
	EndDate openapi_types.Date `form:"end_date" json:"end_date"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// OrgId Organization ID to filter projects.
	OrgId string `form:"org_id" json:"org_id"`

	// PageSize Maximum number of items to return (1-100, default 20).
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken Opaque token for cursor-based pagination.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`

	// SortBy Sort field for projects list.
	SortBy *ListProjectsParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// ListProjectsParamsSortBy defines parameters for ListProjects.
type ListProjectsParamsSortBy string

// ListDatabasesParams defines parameters for ListDatabases.
type ListDatabasesParams struct {
	// PageSize Maximum number of items to return (1-100, default 20).
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken Opaque token for cursor-based pagination.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListCacheRulesParams defines parameters for ListCacheRules.
type ListCacheRulesParams struct {
	// PageSize Maximum number of items to return (1-100, default 20).
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken Opaque token for cursor-based pagination.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListCustomDomainsParams defines parameters for ListCustomDomains.
type ListCustomDomainsParams struct {
	// PageSize Maximum number of items to return (1-100, default 20).
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken Opaque token for cursor-based pagination.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// GetProjectInsightsParams defines parameters for GetProjectInsights.
type GetProjectInsightsParams struct {
	// Range Time range to query. Defaults to 24h.
	Range *GetProjectInsightsParamsRange `form:"range,omitempty" json:"range,omitempty"`

	// Limit Maximum number of top queries to return (1-100).
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetProjectInsightsParamsRange defines parameters for GetProjectInsights.
type GetProjectInsightsParamsRange string

// GetProjectMetricsParams defines parameters for GetProjectMetrics.
type GetProjectMetricsParams struct {
	// Limit Maximum number of recent snapshots to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Region Filter metrics by region code.
	Region *string `form:"region,omitempty" json:"region,omitempty"`
}

// GetProjectUsageParams defines parameters for GetProjectUsage.
type GetProjectUsageParams struct {
	// StartDate Start date (inclusive, YYYY-MM-DD).
	StartDate openapi_types.Date `form:"start_date" json:"start_date"`

	// EndDate End date (inclusive, YYYY-MM-DD).
	EndDate openapi_types.Date `form:"end_date" json:"end_date"`
}

// CreateReplicaJSONRequestBody defines body for CreateReplica for application/json ContentType.
type CreateReplicaJSONRequestBody = CreateReplicaRequest

// McpTransportJSONRequestBody defines body for McpTransport for application/json ContentType.
type McpTransportJSONRequestBody = McpRequest

// SubmitCancellationFeedbackJSONRequestBody defines body for SubmitCancellationFeedback for application/json ContentType.
type SubmitCancellationFeedbackJSONRequestBody = CancellationFeedbackRequest

// UpdateOnboardingProgressJSONRequestBody defines body for UpdateOnboardingProgress for application/json ContentType.
type UpdateOnboardingProgressJSONRequestBody = UpdateOnboardingRequest

// UpdateSpendLimitJSONRequestBody defines body for UpdateSpendLimit for application/json ContentType.
type UpdateSpendLimitJSONRequestBody = UpdateSpendLimitRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest

// CreateDatabaseJSONRequestBody defines body for CreateDatabase for application/json ContentType.
type CreateDatabaseJSONRequestBody = CreateDatabaseRequest

// UpdateDatabaseJSONRequestBody defines body for UpdateDatabase for application/json ContentType.
type UpdateDatabaseJSONRequestBody = UpdateDatabaseRequest

// UpdateCacheRuleJSONRequestBody defines body for UpdateCacheRule for application/json ContentType.
type UpdateCacheRuleJSONRequestBody = UpdateCacheRuleRequest

// CreateCustomDomainJSONRequestBody defines body for CreateCustomDomain for application/json ContentType.
type CreateCustomDomainJSONRequestBody = CreateCustomDomainRequest
